# Generated by Django 4.2.7 on 2023-12-03 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('searchapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('img', models.ImageField(upload_to='pics')),
                ('desc', models.TextField()),
                ('mobile_numer', models.IntegerField(max_length=10)),
                ('colour', models.TextField()),
                ('dob', models.DateField()),
            ],
        ),
        migrations.DeleteModel(
            name='destinations',
        ),
    ]
