# Generated by Django 4.2.7 on 2023-12-03 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('searchapp', '0003_rename_mobile_numer_details_mobile_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='details',
            name='mobile_number',
            field=models.IntegerField(),
        ),
    ]
